# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-23 18:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('upvotes', models.IntegerField()),
                ('status', models.CharField(choices=[('to_do', 'To do'), ('doing', 'Doing'), ('done', 'Done')], max_length=10, unique=True)),
                ('piece_type', models.CharField(choices=[('article', 'Article'), ('report', 'Report')], max_length=10, unique=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
