# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-23 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='piece_type',
            field=models.CharField(choices=[('Article', 'article'), ('Report', 'report')], max_length=10),
        ),
        migrations.AlterField(
            model_name='piece',
            name='status',
            field=models.CharField(choices=[('To do', 'to_do'), ('Doing', 'doing'), ('Done', 'done')], max_length=10),
        ),
    ]
