# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-13 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20190323_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piece',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='piece',
            name='price_point',
            field=models.CharField(choices=[('€150', '150'), ('€250', '250'), ('€500', '500'), ('Email', 'email')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='piece',
            name='piece_type',
            field=models.CharField(choices=[('Bespoke Content', 'bespoke'), ('Recipes Dev', 'recipe'), ('Tastings and Events', 'event')], max_length=20),
        ),
    ]
