# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-14 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20190913_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='piece_type',
            field=models.CharField(choices=[('bespoke', 'Bespoke Content'), ('event', 'Tastings and Events'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='piece',
            name='price_point',
            field=models.CharField(choices=[('150', '€150'), ('250', '€250'), ('500', '€500'), ('email', 'Email')], max_length=10),
        ),
        migrations.AlterField(
            model_name='piece',
            name='status',
            field=models.CharField(choices=[('to_do', 'To do'), ('doing', 'Doing'), ('done', 'Done')], max_length=10),
        ),
    ]
