# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-14 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20190914_1901'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='piece',
            unique_together=set([]),
        ),
    ]
