# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-14 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20190914_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='piece_type',
            field=models.CharField(choices=[('Bespoke Content', 'Bespoke Content'), ('Tastings and Events', 'Tastings and Events'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='piece',
            name='price_point',
            field=models.CharField(choices=[('€150', '€150'), ('€250', '€250'), ('€500', '€500'), ('Email', 'Email')], max_length=10),
        ),
        migrations.AlterField(
            model_name='piece',
            name='status',
            field=models.CharField(choices=[('To do', 'To do'), ('Doing', 'Doing'), ('Done', 'Done')], max_length=10),
        ),
    ]
