# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-14 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20190914_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='status',
            field=models.CharField(choices=[('To do', 'To do'), ('Doing', 'Doing'), ('Customer review', 'Customer review'), ('Done', 'Done')], max_length=10),
        ),
    ]
